<a href="https://colab.research.google.com/github/gustagt/Curso-Extensao-Pandas/blob/main/Aula_01_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Primeiro exemplo de manipulação de dados usando Python Pandas**
## Autor: Gustavo Augusto Ferreira da Silva
## Data: 6 de fevereiro de 2023

In [3]:
# Para instalar, use esse comando!
# !pip install pandas

#Importando o Pandas
import pandas as pd

combustiveis_df = pd.read_excel('ca-2021-02.xlsx')

In [ ]:
# Usa o print para ver o dataframe!
display(combustiveis_df)

In [23]:
display(combustiveis_df.head(30))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
6,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.982,NaN,R$ / litro,VIBRA ENERGIA
7,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.974,NaN,R$ / litro,VIBRA ENERGIA
8,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA ADITIVADA,2021-11-01,7.208,NaN,R$ / litro,VIBRA ENERGIA
9,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.983,NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.197,NaN,R$ / litro,BRANCA
11,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.987,NaN,R$ / litro,BRANCA
12,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.978,NaN,R$ / litro,BRANCA
13,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.989,NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,2021-11-01,7.175,NaN,R$ / litro,BRANCA
15,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,ETANOL,2021-11-01,5.930,NaN,R$ / litro,BRANCA
16,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,DIESEL,2021-11-01,5.955,NaN,R$ / litro,BRANCA
17,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA ADITIVADA,2021-11-01,7.175,NaN,R$ / litro,BRANCA
18,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,DIESEL S10,2021-11-01,5.980,NaN,R$ / litro,BRANCA
19,N,AM,ITACOATIARA,MARCOS ANTONIO DA SILVA CABRAL,03.019.535/0001-00,AVENIDA PARQUE,1012,NaN,CENTRO,69100-000,GASOLINA,2021-11-01,6.990,NaN,R$ / litro,BRANCA
20,N,AM,ITACOATIARA,MARCOS ANTONIO DA SILVA CABRAL,03.019.535/0001-00,AVENIDA PARQUE,1012,NaN,CENTRO,69100-000,ETANOL,2021-11-01,5.890,NaN,R$ / litro,BRANCA
21,N,AM,ITACOATIARA,MARCOS ANTONIO DA SILVA CABRAL,03.019.535/0001-00,AVENIDA PARQUE,1012,NaN,CENTRO,69100-000,DIESEL,2021-11-01,5.890,NaN,R$ / litro,BRANCA
22,N,AM,ITACOATIARA,MARCOS ANTONIO DA SILVA CABRAL,03.019.535/0001-00,AVENIDA PARQUE,1012,NaN,CENTRO,69100-000,DIESEL S10,2021-11-01,5.950,NaN,R$ / litro,BRANCA
23,N,AM,ITACOATIARA,FERNANDO AZEVEDO FILHO,06.992.904/0001-27,RUA BORBA,1667,NaN,IRACY,69100-000,GASOLINA,2021-11-01,6.790,NaN,R$ / litro,BRANCA
24,N,AM,ITACOATIARA,FERNANDO AZEVEDO FILHO,06.992.904/0001-27,RUA BORBA,1667,NaN,IRACY,69100-000,DIESEL,2021-11-01,5.690,NaN,R$ / litro,BRANCA
25,N,AM,ITACOATIARA,EMAQUISON DOS SANTOS FERREIRA,04.280.081/0001-81,AVENIDA TORQUATO TAPAJOS,1887,NaN,PEDREIRAS,69100-000,GASOLINA,2021-11-01,6.990,NaN,R$ / litro,ATEM' S
26,N,AM,ITACOATIARA,EMAQUISON DOS SANTOS FERREIRA,04.280.081/0001-81,AVENIDA TORQUATO TAPAJOS,1887,NaN,PEDREIRAS,69100-000,DIESEL,2021-11-01,5.790,NaN,R$ / litro,ATEM' S
27,N,AM,ITACOATIARA,NOBRE E BRAGA LTDA.,23.039.662/0001-70,ESTRADA STONE,502,NaN,JAUARY,69100-000,GASOLINA,2021-11-01,6.790,NaN,R$ / litro,BRANCA
28,N,AM,ITACOATIARA,NOBRE E BRAGA LTDA.,23.039.662/0001-70,ESTRADA STONE,502,NaN,JAUARY,69100-000,DIESEL,2021-11-01,5.450,NaN,R$ / litro,BRANCA
29,N,AM,ITACOATIARA,ADRIANO MARQUES FRANCO - ME,03.265.623/0001-84,AVENIDA ARMINDO AUZIER,238,NaN,JAUARY,69100-000,GASOLINA,2021-11-01,6.750,NaN,R$ / litro,BRANCA

In [19]:
# Mostra as linhas e colunas
display(combustiveis_df.shape)

(168409, 16)

In [17]:
# Mostra os principais calculos
display(combustiveis_df.describe())

       Valor de Venda  Valor de Compra
count   168409.000000              0.0
mean         6.005184              NaN
std          0.794541              NaN
min          2.849000              NaN
25%          5.339000              NaN
50%          5.859000              NaN
75%          6.699000              NaN
max          8.990000              NaN

In [24]:
#Quais são as colunas e cada tipo de dados ela recebe
print(combustiveis_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 20.6+ MB
None

In [32]:
display(combustiveis_df['Revenda'][0:10])

0              POSTO ARAPIRACA LTDA
1              POSTO ARAPIRACA LTDA
2              POSTO ARAPIRACA LTDA
3              POSTO ARAPIRACA LTDA
4              POSTO ARAPIRACA LTDA
5    AUTO POSTO FREITAS & MAIA LTDA
6    AUTO POSTO FREITAS & MAIA LTDA
7    AUTO POSTO FREITAS & MAIA LTDA
8    AUTO POSTO FREITAS & MAIA LTDA
9    AUTO POSTO FREITAS & MAIA LTDA
Name: Revenda, dtype: object

In [39]:
novo_df = combustiveis_df[['Revenda', 'Municipio', 'Produto', 'Valor de Venda']]

display(novo_df)

,Revenda,Municipio,Produto,Valor de Venda
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799
1,POSTO ARAPIRACA LTDA,ARAPIRACA,ETANOL,5.299
2,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL,5.549
3,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA ADITIVADA,6.899
4,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL S10,5.649
...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,5.859
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,5.448
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580

In [42]:
display(novo_df.loc[3])

Revenda           POSTO ARAPIRACA LTDA
Municipio                    ARAPIRACA
Produto             GASOLINA ADITIVADA
Valor de Venda                   6.899
Name: 3, dtype: object

In [49]:
display(novo_df.loc[9:19])
display(novo_df.loc[9::19])
display(novo_df.loc[9:3:19])
display(novo_df.loc[9::])
display(novo_df.loc[::9])
display(novo_df.loc[::-1])

,Revenda,Municipio,Produto,Valor de Venda
9,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.983
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,GASOLINA,7.197
11,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,ETANOL,5.987
12,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,DIESEL,5.978
13,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.989
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA,7.175
15,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,ETANOL,5.930
16,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,DIESEL,5.955
17,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA ADITIVADA,7.175
18,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.980
19,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,GASOLINA,6.990

,Revenda,Municipio,Produto,Valor de Venda
9,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.983
28,NOBRE E BRAGA LTDA.,ITACOATIARA,DIESEL,5.450
47,POSTO ATLANTICO SUL LTDA,ILHEUS,ETANOL,5.799
66,MP COMERCIO DE COMBUSTIVEIS LTDA,SALVADOR,GASOLINA,6.630
85,POSTO KALILANDIA LTDA,SALVADOR,ETANOL,5.670
...,...,...,...,...
168330,AUTO POSTO SIQUELERO DE ITAPETININGA LTDA,ITAPETININGA,DIESEL,5.059
168349,POSTO EXPOPEC EIRELI,ITUIUTABA,DIESEL,5.458
168368,AEROPOSTO COMERCIO DE COMBUSTIVEIS LTDA,JEQUIE,ETANOL,5.859
168387,AUTO POSTO RAIDEN LTDA.,BAURU,DIESEL S10,5.199
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740

Empty DataFrame
Columns: [Revenda, Municipio, Produto, Valor de Venda]
Index: []

,Revenda,Municipio,Produto,Valor de Venda
9,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.983
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,GASOLINA,7.197
11,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,ETANOL,5.987
12,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,DIESEL,5.978
13,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.989
...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,5.859
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,5.448
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580

,Revenda,Municipio,Produto,Valor de Venda
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799
9,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.983
18,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.980
27,NOBRE E BRAGA LTDA.,ITACOATIARA,GASOLINA,6.790
36,ERMELSON DOS SANTOS FERREIRA,ITACOATIARA,DIESEL S10,5.890
...,...,...,...,...
168372,CAPIXABA COMERCIO DE PRODUTOS AUTOMOTIVOS LTDA...,GUARAPARI,ETANOL,6.070
168381,POSTO DE COMBUSTIVEIS - BEIRA VALAO DE CAMPOS ...,CAMPOS DOS GOYTACAZES,ETANOL,5.799
168390,M W COMERCIO DE COMBUSTIVEIS SERVICOS E ALIMEN...,JEQUIE,ETANOL,5.599
168399,VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...,CAMPOS DOS GOYTACAZES,GASOLINA,7.090
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580

,Revenda,Municipio,Produto,Valor de Venda
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,5.448
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,5.859
...,...,...,...,...
4,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL S10,5.649
3,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA ADITIVADA,6.899
2,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL,5.549
1,POSTO ARAPIRACA LTDA,ARAPIRACA,ETANOL,5.299
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799

In [ ]:
gas_df = novo_df.loc[novo_df['Produto'] == 'GASOLINA']

display(gas_df)

In [53]:
display(gas_df['Valor de Venda'].max())

7.999

In [60]:
print(gas_df[['Revenda', 'Municipio', 'Valor de Venda']].max())

Revenda           ZV POSTO DE SERVIÇO LTDA.
Municipio                           XANXERE
Valor de Venda                        7.999
dtype: object